---
#station_date:出发日期，格式ex：2018-01-06
#station_trains:过滤车次，格式ex：
                #    - "G1353"
                #    - "G1329"
                #    - "G1355"
                #    - "G1303"
                #    - "G1357"
                #    - "G1305"
                #    - "G1359"
                #    - "G1361"
                #    - "G1373"
                #    - "G1363"
#from_station: 始发站
#to_station: 到达站
#set_type: 坐席(商务座,二等座,特等座,软卧,硬卧,硬座,无座)
#is_more_ticket:余票不足是否自动提交
#select_refresh_interval:抢票刷新间隔时间，1为一秒，0.1为100毫秒，以此类推 如果捡漏推荐为1秒，刷票设置0.01
#expect_refresh_interval:售票未开始，等待刷新间隔时间，1为一秒，0.1为100毫秒，以此类推
#ticket_black_list:加入小黑屋的等待时间，默认3 min
#enable_proxy:是否开启代理模式，代理速度比较慢，如果是抢票阶段，不建议开启
#ticke_peoples: 乘客
#damatu：打码兔账号，用于自动登录
#is_aotu_code是否自动打码，如果选择Ture,则调用打码兔打码，默认不使用打码兔
set:
  station_date: "2018-02-10"
  station_trains:
    - "T17"
    - "T297"
#    - "G2365"
#    - "G1371"
#    - "G1377"
#    - "G1329"
#    - "G1305"
#    - "G1359"
#    - "G1361"
#    - "G1373"
#    - "G1363"
#    - "G4933"
  from_station: "北京"
  to_station: "牡丹江"
  set_type:
    - "硬卧"
  is_more_ticket: True
  ticke_peoples:
    - ""
    - ""
  12306count:
#    - uesr: "1"
#    - pwd: "649823049lilymin"
    - uesr: "@qq.com"
    - pwd: "QWERTY"

select_refresh_interval: 0.1
expect_refresh_interval: 0.3
ticket_black_list_time: 3
is_aotu_code: False
#enable_proxy: False

damatu:
  uesr: ""
  pwd: "wen1995"



