---
set:
  # 出发日期，格式ex：2018-01-06
  station_dates:
    - "2018-09-05"

  # 过滤车次，格式ex：- "G1353" - "G1329"
  station_trains:
    - "G6504"

  # 出发城市，比如深圳北，就填深圳就搜得到
  from_station: "深圳"

  # 到达城市 比如深圳北，就填深圳就搜得到
  to_station: "广州"

  # 座位 多个座位ex: - "二等座" - "一等座"
  set_type:
    - "二等座"

  # 余票不足是否自动提交，目前应该没什么卵用
  is_more_ticket: True

  # 乘车人 多个乘车人ex: - "张三" - "李四"
  ticke_peoples:
    - ""
  # 12306登录账号
  12306account:
    - uesr: ""
    - pwd: ""

select_refresh_interval: 1

# 加入小黑屋时间，此功能为了防止僵尸票导致一直下单不成功错过正常的票
ticket_black_list_time: 5

# 自动打码
is_auto_code: False

# 打码平台， 2 为若快平台（目前只支持若快平台打码，打码兔已经关闭）, 若快注册地址：http://www.ruokuai.com/client/index?6726
auto_code_type: 2

# 打码平台账号
auto_code_account:
  uesr: ""
  pwd: ""

#  邮箱配置，如果抢票成功，将通过邮件配置通知给您
#  列举163
#  email: "xxx@163.com"
#  notice_email_list: "123@qq.com"
#  username: "xxxxx"
#  password: "xxxxx
#  host: "smtp.163.com"
#  列举qq  ，qq设置比较复杂，需要在邮箱-->账户-->开启smtp服务，取得授权码==邮箱登录密码
#  email: "xxx@qq.com"
#  notice_email_list: "123@qq.com"
#  username: "xxxxx"
#  password: "授权码"
#  host: "smtp.qq.com"
email_conf:
  is_email: True
  email: "@qq.com "
  notice_email_list: "@qq.com"
  username: ""
  password: ""
  host: "smtp.qq.com"

# 是否开启cdn查询，可以更快的检测飘飘 1为开启，2为关闭
is_cdn: 2

# 下单接口分为两种，1 为快速下单，2 是普通下单
order_type: 1



